apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: hyteria-mcp
spec:
  podSelector: {}  # 네임스페이스 내 모든 Pod에 적용
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0  # 모든 IP로 허용