apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyteria-mcp.fullname" . }}-config
  labels:
    {{- include "hyteria-mcp.labels" . | nindent 4 }}
data:
  log-level: {{ .Values.config.logLevel | quote }} 
